server:
  port: 8090
  servlet:
    context-path: "/bo"

spring:
  config:
    import: "application-core.yml"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    access-token:
      secret-key: test
    refresh-token:
      secret-key: test

springdoc:
  packages-to-scan: org.winners.backoffice
  api-docs:
    enabled: true
    path: /api/docs/json
  swagger-ui:
    enabled: true
    path: /api/docs
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    disable-swagger-default-url: false
  model-and-view-allowed: true
  group-configs:
    - group: V1
      paths-to-match:
        - /v1/**