spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:winners;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        trace: false
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
    generate-ddl: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect